name: CI-CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/SSAEM_SSAENG
            git config --global --add safe.directory /home/ubuntu/SSAEM_SSAENG
            sudo add-apt-repository ppa:git-core/ppa 
            sudo apt update
            sudo apt install git
            sudo git pull
            sudo npm update
            sudo npm install
            sudo pm2 reload all
